import { NextResponse } from 'next/server'
import { z } from 'zod'
import { createAdminClient } from '@/lib/supabase/admin'
import { isValidAdminToken } from '@/lib/portugal-auth'
import { sendSms } from '@/lib/notifications/channels/sms'
import { getEnv } from '@/lib/env'

const schema = z.object({
  count: z.number().int().min(1).max(100),
})

type Registration = { id: string; name: string; email: string; phone: string }
type Winner = { id: string; registration_id: string; qr_token: string }

export async function POST(request: Request) {
  const token = request.headers.get('x-admin-token')
  if (!isValidAdminToken(token)) {
    return NextResponse.json({ error: 'Nao autorizado' }, { status: 401 })
  }

  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Pedido invalido' }, { status: 400 })
  }

  const parsed = schema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: 'count invalido' }, { status: 422 })
  }

  const { count } = parsed.data
  const supabase = createAdminClient()
  const { NEXT_PUBLIC_APP_URL: appUrl } = getEnv()

  // Anti-double-draw: check if any winners exist
  const { count: existingCount } = await supabase
    .from('portugal_winners')
    .select('id', { count: 'exact', head: true })

  if ((existingCount ?? 0) > 0) {
    return NextResponse.json({ error: 'Sorteio ja foi realizado.' }, { status: 409 })
  }

  // Fetch all registrations, shuffle in JS (Fisher-Yates), pick first N
  const { data: registrations, error: drawError } = await supabase
    .from('portugal_registrations')
    .select('id, name, email, phone')
    .order('created_at')
    .limit(10000)
    .returns<Registration[]>()

  if (drawError || !registrations || registrations.length === 0) {
    return NextResponse.json({ error: 'Sem registos para sortear.' }, { status: 400 })
  }

  // Fisher-Yates shuffle
  const shuffled = [...registrations]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  const selected = shuffled.slice(0, Math.min(count, shuffled.length))

  // Insert winners (qr_token generated by Postgres DEFAULT)
  const { data: winners, error: insertError } = await supabase
    .from('portugal_winners')
    .insert(selected.map(r => ({ registration_id: r.id })))
    .select('id, registration_id, qr_token')
    .returns<Winner[]>()

  if (insertError || !winners) {
    return NextResponse.json({ error: 'Erro ao guardar vencedores.' }, { status: 500 })
  }

  // Send SMS to each winner; don't fail the whole draw if one SMS fails
  const smsResults = await Promise.allSettled(
    winners.map(async (w) => {
      const reg = selected.find(r => r.id === w.registration_id)!
      const url = `${appUrl}/portugal/qr/${w.qr_token}`
      const message = `Parabens ${reg.name}! Ganhaste uma cerveja no jogo de Portugal. Mostra este QR ao staff do bar: ${url}`
      await sendSms({ to: reg.phone, message })
      await supabase
        .from('portugal_winners')
        .update({ sms_sent_at: new Date().toISOString() })
        .eq('id', w.id)
      return { name: reg.name, phone: reg.phone, qr_token: w.qr_token }
    })
  )

  const results = smsResults.map((r, i) => {
    const reg = selected[i]
    if (r.status === 'fulfilled') return r.value
    return {
      name: reg.name,
      phone: reg.phone,
      qr_token: winners[i].qr_token,
      sms_error: String((r as PromiseRejectedResult).reason),
    }
  })

  return NextResponse.json({ winners: results })
}
