// ONE-SHOT: add all 237 ActivoBank Lounge contacts to newsletter list. Delete after use.
import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'

const LIST_ID = '8b2bacaa-3178-42bb-bf1a-dcf0744c6e3d'
const ORG_ID_PLACEHOLDER = 'org' // resolved from list row
const ONE_SHOT_TOKEN = 'add-activobank-contacts-2026'

const ALL_CONTACTS = [
  { name: 'Abner Moreno', email: 'abnermoreno@gmail.com' },
  { name: 'Adérito Domingos Gama', email: 'aderitodimingos.9@gmail.com' },
  { name: 'Afonso', email: 'afonsoventuzelos@gmail.com' },
  { name: 'Alex', email: 'alexandrerua4@gmail.com' },
  { name: 'Alex', email: 'alex93_nike@hotmail.com' },
  { name: 'Alex Alexandre', email: 'alexsma7@hotmail.com' },
  { name: 'Algassimo Djalo', email: 'djalodjery2023@gmail.com' },
  { name: 'Allan Teixeira Da Mota', email: 'allanteix@outlook.com' },
  { name: 'Ana Julia Rodrigues', email: 'anajuliaerodrigues@gmail.com' },
  { name: 'Ana Paula', email: 'paulagomes0311@hotmail.com' },
  { name: 'Ana Paula', email: 'paulasjr1968@gmail.com' },
  { name: 'Anapaula', email: 'apfolha@gmail.com' },
  { name: 'Anas', email: 'anas.afirrahh@gmail.com' },
  { name: 'Ângela', email: 'angela@mundunobu.org' },
  { name: 'Anthony', email: 'anthony.nimpa23@gmail.com' },
  { name: 'Antonin', email: 'antoningoosse@gmail.com' },
  { name: 'António Lourenço', email: 'ajm_lourenco@hotmail.com' },
  { name: 'Antonio Pina', email: 'antoniofradepina@gmail.com' },
  { name: 'Antonio Santos', email: 'antoniosantos198268@gmail.com' },
  { name: 'Aristides', email: 'menezesdegarcia@gmail.com' },
  { name: 'Armando Alejandro Garcia', email: 'armando93931@gmail.com' },
  { name: 'Artur', email: 'maraca.2005.f@gmail.com' },
  { name: 'Asgad Osman Elmaki', email: 'osman.asgad@gmail.com' },
  { name: 'Ashtar', email: 'ashtarkt@gmail.com' },
  { name: 'Augusto Andra', email: 'josejaab@gmail.com' },
  { name: 'Beatriz Fernandes', email: 'beaisa85@gmail.com' },
  { name: 'Benicio Teixeira', email: 'benibilis@gmail.com' },
  { name: 'Bennouna Mounia', email: 'bennouna.mounia@gmail.com' },
  { name: 'Bernardo', email: 'bernardo.abrantes@hotmail.com' },
  { name: 'Bikky Shrestha', email: 'bikky.stha1@gmail.com' },
  { name: 'Cansu Colak', email: 'cansu_cc@hotmail.de' },
  { name: 'Carla Garcia', email: 'carlagarcia84@icloud.com' },
  { name: 'Carlos', email: 'multiservicioscorga@hotmail.com' },
  { name: 'Carlos Alberto Garcia Abundez', email: 'charlie.ga29@gmail.com' },
  { name: 'Carlos Correa', email: 'carlovsc@gmail.com' },
  { name: 'Carlos Felix', email: 'felixcarlos0908@gmail.com' },
  { name: 'Carole', email: 'carolegosselin@live.fr' },
  { name: 'Carolina Andrade', email: 'carolcervino@gmail.com' },
  { name: 'Carolina Batista', email: 'carolina.batista2003@gmail.com' },
  { name: 'Cátia Cascão', email: 'catiuscacascao@gmail.com' },
  { name: 'Christoph', email: 'henning.schulze@dslissabon.com' },
  { name: 'Cidália de Jesus', email: 'cidaliajsantos@gmail.com' },
  { name: 'Claudia Andrade', email: 'claucami21@gmail.com' },
  { name: 'Claudia Dieb', email: 'claudiadieb@hotmail.com' },
  { name: 'Claudia Reis', email: 'claudiareis1011@gmail.com' },
  { name: 'Claudio', email: 'hochmanclaudio@gmail.com' },
  { name: 'Claudia Correia Pires', email: 'claudiacorreiapires@hotmail.com' },
  { name: 'Costantino Daniel', email: 'danielcostantino01@gmail.com' },
  { name: 'Cristina', email: 'ccjoon@icloud.com' },
  { name: 'Damla', email: 'damlag.00@hotmail.com' },
  { name: 'Daniel Silva', email: 'daneil.passalio@gmail.com' },
  { name: 'Dari', email: 'andremrc@hotmail.it' },
  { name: 'David Figueroa', email: 'davosandovalpt@gmail.com' },
  { name: 'David Pinheiro', email: 'david.franco.pinheiro@gmail.com' },
  { name: 'Denis François Barbateau', email: 'denis.barbateau@gmail.com' },
  { name: 'Diego Rodríguez Sanche', email: 'diegors_2102@hotmail.com' },
  { name: 'Dina Manso', email: 'dinamanso@gmail.com' },
  { name: 'Drouet', email: 'bdrouet@hotmail.com' },
  { name: 'Duarte Afonso', email: 'duarte8afonso@gmail.com' },
  { name: 'Edmar Nascimento', email: 'edmarn@gmail.com' },
  { name: 'Eduardo Bentes Monteiro', email: 'a20131074@agepm.pt' },
  { name: 'Eduardo Filho', email: 'eduardodfilho.057@gmail.com' },
  { name: 'Eliomaria Panta da Conceição', email: 'elipantaa@gmail.com' },
  { name: 'Emanuele Juliana Fonseca', email: 'emanuelecalado@gmail.com' },
  { name: 'Enzo', email: 'enzomzc1@gmail.com' },
  { name: 'Erick Nava', email: 'erick.nava.hdez@gmail.com' },
  { name: 'Eugenio Silva', email: 'mushu172@gmail.com' },
  { name: 'Evhen Dubrov', email: 'evhendubrov@gmail.com' },
  { name: 'Fabio', email: 'fabiodasilvabarros21@gmail.com' },
  { name: 'Fábio Ferreira', email: 'busines57@hotmail.com' },
  { name: 'Fabiola', email: 'fabiola.panetti0@gmail.com' },
  { name: 'Fede Pochat', email: 'feducho@mail.com' },
  { name: 'Felipe', email: 'ftrigueros2@gmail.com' },
  { name: 'Felipe da Silva Santos', email: 'frota_lukyy@hotmail.com' },
  { name: 'Felipe Silva', email: 'felipe_dias-01@hotmail.com' },
  { name: 'Fernanda', email: 'fergabundez@gmail.com' },
  { name: 'Fernando Jorge Luz', email: 'fernando.jorge.luz@sapo.pt' },
  { name: 'Filipa', email: 'filipavcortes@outlook.pt' },
  { name: 'Francesca Tumiatti', email: 'francescatumiatti5@gmail.com' },
  { name: 'Francisco Godinho', email: 'godinho0203francisco@gmail.com' },
  { name: 'Francisco João de Siqueira Neto', email: 'ele.siqueira@gmail.com' },
  { name: 'Frederico Cordeiro', email: 'fredy_cordeiro_9@hotmail.com' },
  { name: 'Gabriel Inácio Ferreira Luiz Amaral', email: 'gabrielnc6@gmail.com' },
  { name: 'Gabriel Pereira Ferraz', email: 'gabrielpereraferraz@gmail.com' },
  { name: 'Gastão Obega', email: 'obegagastao66@gmail.com' },
  { name: 'Geraldo A Da Silva', email: 'dasilvageraldo74@gmail.com' },
  { name: 'Ghita', email: 'ghita.thiyfa@skema.edu' },
  { name: 'Goncalo', email: 'goncalo28santos2007@gmail.com' },
  { name: 'Gonçalo', email: 'goncalodslalves@gmail.com' },
  { name: 'Gonçalo Antunes', email: 'gongasantunes2008@gmail.com' },
  { name: 'Guilherme', email: 'gui.costa09@hotmail.com' },
  { name: 'Guilherme', email: 'guiarranhado@gmail.com' },
  { name: 'Guilherme', email: 'guilhermemaggessi30@gmail.com' },
  { name: 'Guilherme Oliveira', email: 'guimarquesoliveira@gmail.com' },
  { name: 'Hugo Leonardo Cabral Bezerra e Silva', email: 'hugoleonardocabral805@gmail.com' },
  { name: 'Hugo Rafael Soares', email: 'hrafaelsoares83@gmail.com' },
  { name: 'Hugo Silva', email: 'hrodrigosilva17@gmail.com' },
  { name: 'Inês', email: 'inesfradiquebastos@gmail.com' },
  { name: 'Izabela', email: 'izabela.gajewska2000@gmail.com' },
  { name: 'Janaína Hohenfeld Araújo', email: 'janahohenfeld7@gmail.com' },
  { name: 'Jéssica', email: 'jekas170322@gmail.com' },
  { name: 'Joana Pina', email: 'joanapina04@outlook.com' },
  { name: 'Joanna Dragon', email: 'joannadragon384@gmail.com' },
  { name: 'João', email: 'hurrahs.94-law@icloud.com' },
  { name: 'João', email: 'joao-alves-28@hotmail.com' },
  { name: 'João Delgado', email: 'putopersie@gmail.com' },
  { name: 'João Francisco Fonseca Seixas', email: 'joaoseixasgrh@gmail.com' },
  { name: 'João Oliveira', email: 'joaorooliveira04@gmail.com' },
  { name: 'João Pedro Pires da Costa', email: 'joaopiresc@gmail.com' },
  { name: 'João Tiago Virote', email: 'joaovirote@gmail.com' },
  { name: 'Jonathan Ibarra', email: 'jonathanibarracoronel@gmail.com' },
  { name: 'Jorge Moura', email: 'jorge.moura@live.com' },
  { name: 'Jose Ricardo', email: 'ricardo.nunes.1912@gmail.com' },
  { name: 'Jossette', email: 'simple.personal@gmail.com' },
  { name: 'Julio Vigueras', email: 'juliocrv20@gmail.com' },
  { name: 'Junior Rosa', email: 'jr.rosa01@gmail.com' },
  { name: 'Kecia Franco', email: 'keciacarolyneee@gmail.com' },
  { name: 'Kristina', email: 'stoyan.kristina@hotmail.com' },
  { name: 'Kyrylo', email: 'jiecoryi3@gmail.com' },
  { name: 'Laura', email: 'lixfat@gmail.com' },
  { name: 'Laura', email: 'laura00romeirosantos@gmail.com' },
  { name: 'Laura Cristina', email: 'lauracristinaas@gmail.com' },
  { name: 'Lauréline Puille', email: 'puillelaureline@gmail.com' },
  { name: 'Leandro', email: 'leandrofenix@gmail.com' },
  { name: 'Leila Koweindl', email: 'leila.koweindl@bluewin.ch' },
  { name: 'Leonardo Alves', email: '29500@aefernandopessoa.edu.pt' },
  { name: 'Leonardo Lima', email: 'leolimatvde@gmail.com' },
  { name: 'Leonor Ribeiro', email: 'leonorkkribeiro@gmail.com' },
  { name: 'Letícia Leão', email: 'leticialeaos.20@gmail.com' },
  { name: 'Liliana', email: 'liliana@mundunobu.org' },
  { name: 'Liliana', email: 'lilianapaw@gmail.com' },
  { name: 'Lisa Vogel', email: 'lisachf@gmx.de' },
  { name: 'Lucas', email: 'gushier.edict4e@icloud.com' },
  { name: 'Lucia', email: 'suarezcerda@gmail.com' },
  { name: 'Luciana Menezes Fernandes', email: 'luciana@soperimoveis.com.br' },
  { name: 'Luis Morais', email: 'luiscrodriguesmorais@gmail.com' },
  { name: 'Manuel', email: 'mm.veigagomes7@gmail.com' },
  { name: 'Manuel Castañeda', email: 'mldigital77@gmail.com' },
  { name: 'Manuel Lopes', email: 'maialopes19@gmail.com' },
  { name: 'Mar', email: 'mbayemar@hotmail.com' },
  { name: 'Marcos', email: 'marcos33@live.com.pt' },
  { name: 'Marcos Daniel Da Silva', email: 'mdssilva26@gmail.com' },
  { name: 'Margarida', email: 'margaridat1997@gmail.com' },
  { name: 'Margarida Correia', email: 'margarida.correia121@gmail.com' },
  { name: 'Margarida Nogueira', email: 'margaridasnogueira@hotmail.com' },
  { name: 'Maria', email: 'mariatrabalhos29@gmail.com' },
  { name: 'Maria Bohorquez Gutierrez', email: 'maryangelbohorquez25@gmail.com' },
  { name: 'Maria Clara', email: 'claraalvescanutto@gmail.com' },
  { name: 'Maria Gutiérrez', email: 'lahoraddemariangel@gmail.com' },
  { name: 'Maria Moreira', email: 'ms.alves.moreiraa@gmail.com' },
  { name: 'Maria Queiroz', email: 'mlqo1756@gmail.com' },
  { name: 'María Soledad Chamorro Navarrete', email: 'chilpa_chole@hotmail.com' },
  { name: 'Mariana Ayala', email: 'marianaayalab@gmail.com' },
  { name: 'Mário Carvalho', email: 'mario00carvalho@gmail.com' },
  { name: 'Martim', email: 'martimcharrua.mc@gmail.com' },
  { name: 'Martim Cardoso', email: 'martimcardoso112011@gmail.com' },
  { name: 'Mathis', email: 'mathisgia16@gmail.com' },
  { name: 'Matilda Wikström', email: 'matildaaaw@gmail.com' },
  { name: 'Mauro', email: 'maurocgil@gmail.com' },
  { name: 'Maya', email: 'wildfeat@yandex.ru' },
  { name: 'Miguel Pais', email: 'miguelandradepais@gmail.com' },
  { name: 'Miqueias', email: 'm.astronomia@icloud.com' },
  { name: 'Mireille Morones', email: 'mireillemorones@yahoo.com' },
  { name: 'Miriam Vieira', email: 'miriamsv02@gmail.com' },
  { name: 'Mohammad Abdul Hannan', email: 'mahannan.pt@gmail.com' },
  { name: 'Mohammad Islam', email: 'kickmhk@gmail.com' },
  { name: 'Mouad Tribak', email: 'tribak.m@gmail.com' },
  { name: 'Murielle Gaspar', email: 'muriellegaspar@hotmail.com' },
  { name: 'Nahid Sanganian', email: 'nahidsangany@gmail.com' },
  { name: 'Natalia Raquel Ribeiro Martins', email: 'natalia.rrm@hotmail.com' },
  { name: 'Nathaly Oliveira', email: 'natylisboa02@gmail.com' },
  { name: 'Nathalya', email: 'nathalyaleaal@outlook.com' },
  { name: 'Nikola', email: 'nikolaitsmee@gmail.com' },
  { name: 'Nuno', email: 'ngpocas@gmail.com' },
  { name: 'Nuno Alfarroba', email: 'nuno.c.alf@gmail.com' },
  { name: 'Nuno Gonçalves', email: 'gnuno122@gmail.com' },
  { name: 'Nuno Neves', email: 'nunneves@icloud.com' },
  { name: 'Patricia', email: 'patriciacorreia.2411@gmail.com' },
  { name: 'Patricio Briones Rebolledo', email: 'patricio.briones.r@hotmail.cl' },
  { name: 'Paula', email: 'pgrato@sapo.pt' },
  { name: 'Pedro', email: 'pfigueiredo2006@gmail.com' },
  { name: 'Pedro', email: 'pedrohjuniiorbio@gmail.com' },
  { name: 'Pedro', email: 'peter.tarrana@gmail.com' },
  { name: 'Pedro Alexandre Dias da Costa Malheiro', email: 'pmalheiro8@gmail.com' },
  { name: 'Pedro Ferreira', email: 'pedro18castro@gmail.com' },
  { name: 'Pedro Filipe', email: 'pedrofcf11@gmail.com' },
  { name: 'Pedro Henrique da Costa', email: 'ph.mcosta@hotmail.com' },
  { name: 'Pedro Mendes', email: 'pedromendescatij1998@gmail.com' },
  { name: 'Pedro Nascimento', email: 'progpedro@gmail.com' },
  { name: 'Pedro Pires', email: 'nogueirapires@gmail.com' },
  { name: 'Rafael Raimundo', email: 'rafaelraimundoa03@gmail.com' },
  { name: 'Raphaela', email: 'rodriguessraphalea@gmail.com' },
  { name: 'Rebeca Ferreira da Silva', email: 'rebecafsillva@gmail.com' },
  { name: 'Ricardo Nogueira', email: 'rbnogueira1970@gmail.com' },
  { name: 'Rija Andriana', email: 'dinorija@gmail.com' },
  { name: 'Rita', email: 'ritamrc18@gmail.com' },
  { name: 'Rita', email: 'anaritasaias@gmail.com' },
  { name: 'Rita', email: 'ritasantos1893@hotmail.com' },
  { name: 'Rodrigo', email: 'rodmiguel23@gmail.com' },
  { name: 'Rodrigo', email: '24rodrioliveira@gmail.com' },
  { name: 'Rodrigo Amaro', email: 'rodrigoamaro2006@gmail.com' },
  { name: 'Roger Koweindl', email: 'r.koweindl@bluewin.ch' },
  { name: 'Roshnan', email: 'roshnanaylia123@icloud.com' },
  { name: 'Ruanda', email: 'ruanda.tavares94@gmail.com' },
  { name: 'Rui', email: 'rui.simsim52@gmail.com' },
  { name: 'Rui Sousa', email: 'ruxsousa@gmail.com' },
  { name: 'Sandra Pereira', email: 'sandrafaisca71@hotmail.com' },
  { name: 'Sandro Matos', email: 'luso30@sapo.pt' },
  { name: 'Santiago Santos', email: 's.boanova.s@gmail.com' },
  { name: 'Sara Assis dos Santos Macedo', email: 'saraassismacedo@gmail.com' },
  { name: 'Sendhy', email: 'sendhys@gmail.com' },
  { name: 'Sergio Magalhaes da Silva', email: 'sermagalhaes@gmail.com' },
  { name: 'Simão Serafim', email: 'simaoserafim2005@gmail.com' },
  { name: 'Sofia', email: 'sofiiherrera03@gmail.com' },
  { name: 'Sofia Marques', email: 'sofiamarquesx@gmail.com' },
  { name: 'Sonia Garces Carmona', email: 'garcarso@hotmail.com' },
  { name: 'Stenio Santos Goncalves', email: 'steniosantos111@gmail.com' },
  { name: 'Susana Ferreira', email: 'susana_ferreira795@hotmail.com' },
  { name: 'Tailla Rosa', email: 'tai.ramona@gmail.com' },
  { name: 'Tatiana', email: 'tatiana_c@sapo.pt' },
  { name: 'Telma Pereira', email: 'telma.lm.pereira@gmail.com' },
  { name: 'Thomas Bonnet', email: 'tbonnet934@gmail.com' },
  { name: 'Tiago', email: 'tiago.rosado13@gmail.com' },
  { name: 'Tiago Novais', email: 'tiagoquaresmanovais@gmail.com' },
  { name: 'Trischna Martins', email: 'trischna.martins@gmail.com' },
  { name: 'Umaro Jau', email: 'umarojau77@gmail.com' },
  { name: 'Vanda Carneiro', email: 'vanda.morna@gmail.com' },
  { name: 'Vanessa', email: 'vdini.vd@gmail.com' },
  { name: 'Vera Rocha', email: 'verarocha95@hotmail.com' },
  { name: 'Vicente Vieira', email: 'vicente-corte-vieira@hotmail.com' },
  { name: 'Víctor Chavez', email: 'victor.ariel.rivera20@gmail.com' },
  { name: 'Vitor', email: 'vitorrodrigueseuw@gmail.com' },
  { name: 'Vitor Hugo', email: 'vitorhnunes@icloud.com' },
  { name: 'Viviany', email: 'vivyehenry@gmail.com' },
  { name: 'Wally Loaiza', email: 'aortizloaiza@gmail.com' },
  { name: 'Yara', email: 'iararodrigues233@gmail.com' },
  { name: 'Yehor', email: 'triptofo@gmail.com' },
]

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  if (searchParams.get('token') !== ONE_SHOT_TOKEN) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const supabase = createAdminClient()

  // Get org_id from the list
  const { data: list } = await supabase
    .from('marketing_lists')
    .select('organization_id')
    .eq('id', LIST_ID)
    .single()

  if (!list) return NextResponse.json({ error: 'list not found' }, { status: 404 })

  const seen = new Set<string>()
  const rows = ALL_CONTACTS
    .filter(c => {
      const k = c.email.toLowerCase()
      if (seen.has(k)) return false
      seen.add(k)
      return true
    })
    .map(c => ({
      list_id: LIST_ID,
      email: c.email.toLowerCase(),
      name: c.name,
      organization_id: list.organization_id,
      status: 'active' as const,
    }))

  const { error } = await supabase
    .from('marketing_contacts')
    .upsert(rows, { onConflict: 'list_id,email', ignoreDuplicates: true })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({ inserted: rows.length, list_id: LIST_ID })
}
